language: node_js
node_js:
    - stable

notifications:
    email: true
    slack: webhouseteam:82qu1PX5R5wkYNCW5x6fVlhu

script:
  - yarn
  - yarn build
  - cp ./build/index.html ./build/200.html

deploy:
  provider: surge
  project: ./build/
  domain: odeumcodelite.surge.sh
  skip_cleanup: true
  on:
    all_branches: true
